import { useMemo, useState } from "react";
import type { ReviewRecord, ReviewStatus } from "../lib/dataReview.ts";
import { STAGES, type Stage } from "../lib/types.ts";

const STATUS_LABEL: Record<ReviewStatus, string> = {
  not_reviewed: "Not reviewed",
  verified: "Verified",
  needs_revision: "Needs revision",
  approved_with_caveat: "Approved with caveat",
};

type SortKey = "review_id" | "stage" | "row_count" | "missing_value_count" | "review_status";

// Internal, development-only data review sheet (issue #16) — one real
// record per exhibit, generated by scripts/generate-data-review.ts from
// the same public/data/talent.json + content/report-crosswalk.csv every
// other route already reads. `records` arrives as a build-time prop
// (see src/pages/dev/data-review.astro) — this component only searches,
// filters, and sorts; it never recomputes a value the generation script
// already computed, so the CSV/JSON/HTML outputs can never drift apart.
export function DataReview({ records }: { records: ReviewRecord[] }) {
  const [query, setQuery] = useState("");
  const [stageFilter, setStageFilter] = useState<Stage | "all">("all");
  const [statusFilter, setStatusFilter] = useState<ReviewStatus | "all">("all");
  const [warningsOnly, setWarningsOnly] = useState(false);
  const [sortKey, setSortKey] = useState<SortKey>("review_id");
  const [expanded, setExpanded] = useState<string | null>(null);

  // Nonblocking warning categories (issue #16's own list) — computed here
  // from fields the generation script already populated, not a second
  // parallel set of thresholds hardcoded into the script itself.
  const warningsFor = (r: ReviewRecord): string[] => {
    const warnings: string[] = [];
    if (r.missing_value_count > 0) warnings.push(`${r.missing_value_count} missing value(s)`);
    if (r.row_count > 0 && r.row_count < 5) warnings.push("short time series (<5 rows)");
    if (r.projected_value_count > 0) warnings.push("contains projected values");
    if (r.estimated_value_count > 0) warnings.push("contains estimated values");
    if (r.series_count > 6) warnings.push(`${r.series_count} series (>6 default picker threshold)`);
    if (!r.has_chart_svg) warnings.push("no static SVG fallback (ranked-bar/table shape)");
    if (r.caveat) warnings.push("has a data-quality caveat");
    return warnings;
  };

  const q = query.trim().toLowerCase();
  const filtered = useMemo(() => {
    return records.filter((r) => {
      if (stageFilter !== "all" && r.stage !== stageFilter) return false;
      if (statusFilter !== "all" && r.review_status !== statusFilter) return false;
      if (warningsOnly && warningsFor(r).length === 0) return false;
      if (q && !`${r.exhibit_id} ${r.title} ${r.source}`.toLowerCase().includes(q)) return false;
      return true;
    });
  }, [records, stageFilter, statusFilter, warningsOnly, q]);

  const sorted = useMemo(() => {
    return [...filtered].sort((a, b) => {
      if (sortKey === "row_count" || sortKey === "missing_value_count") return b[sortKey] - a[sortKey];
      return String(a[sortKey]).localeCompare(String(b[sortKey]));
    });
  }, [filtered, sortKey]);

  return (
    <div>
      <div className="pill" style={{ marginBottom: 12 }}>
        {records.length} real exhibits reviewed · {records.filter((r) => r.review_status === "not_reviewed").length} not yet reviewed
      </div>

      <div className="tab-bar" style={{ marginBottom: 10 }}>
        <input
          type="search"
          className="search-input"
          placeholder="Search by id, title, or source…"
          aria-label="Search review records"
          value={query}
          onChange={(e) => setQuery(e.target.value)}
        />
        <select aria-label="Filter by stage" value={stageFilter} onChange={(e) => setStageFilter(e.target.value as Stage | "all")}>
          <option value="all">All stages</option>
          {STAGES.map((s) => (
            <option key={s.id} value={s.id}>{s.label}</option>
          ))}
        </select>
        <select aria-label="Filter by review status" value={statusFilter} onChange={(e) => setStatusFilter(e.target.value as ReviewStatus | "all")}>
          <option value="all">Any review status</option>
          {(Object.keys(STATUS_LABEL) as ReviewStatus[]).map((s) => (
            <option key={s} value={s}>{STATUS_LABEL[s]}</option>
          ))}
        </select>
        <label style={{ display: "flex", alignItems: "center", gap: 4, fontSize: 12 }}>
          <input type="checkbox" checked={warningsOnly} onChange={(e) => setWarningsOnly(e.target.checked)} />
          Warnings only
        </label>
        <select aria-label="Sort by" value={sortKey} onChange={(e) => setSortKey(e.target.value as SortKey)}>
          <option value="review_id">Sort: exhibit id</option>
          <option value="stage">Sort: stage</option>
          <option value="row_count">Sort: row count</option>
          <option value="missing_value_count">Sort: missing values</option>
          <option value="review_status">Sort: review status</option>
        </select>
      </div>

      <div className="trend-note" style={{ marginBottom: 8 }}>{sorted.length} of {records.length} records shown.</div>

      <table className="downloads-table">
        <thead>
          <tr>
            <th>Exhibit</th>
            <th>Stage</th>
            <th>Date range</th>
            <th>Rows</th>
            <th>Warnings</th>
            <th>Status</th>
            <th>Details</th>
          </tr>
        </thead>
        <tbody>
          {sorted.map((r) => {
            const warnings = warningsFor(r);
            return (
              <tr key={r.review_id}>
                <td>
                  <strong>{r.exhibit_id}</strong>
                  <div className="trend-note">{r.title}</div>
                </td>
                <td>{r.stage}</td>
                <td>{r.first_period && r.last_period ? `${r.first_period}–${r.last_period}` : "—"}</td>
                <td>{r.row_count}</td>
                <td>
                  {warnings.length === 0 ? (
                    <span aria-label="No warnings">—</span>
                  ) : (
                    <span>{warnings.length} warning{warnings.length === 1 ? "" : "s"}</span>
                  )}
                </td>
                <td>{STATUS_LABEL[r.review_status]}</td>
                <td>
                  <button
                    type="button"
                    className="link-btn"
                    aria-expanded={expanded === r.review_id}
                    onClick={() => setExpanded((prev) => (prev === r.review_id ? null : r.review_id))}
                  >
                    {expanded === r.review_id ? "Hide" : "Show"}
                  </button>
                  {expanded === r.review_id && (
                    <dl className="methodology-fields" style={{ marginTop: 6 }}>
                      <dt>Source</dt>
                      <dd>{r.source}</dd>
                      <dt>Report reference</dt>
                      <dd>{r.report_reference}</dd>
                      <dt>First → last value</dt>
                      <dd>{r.first_value || "—"} → {r.last_value || "—"} (Δ {r.absolute_change || "—"}, {r.relative_change || "—"})</dd>
                      <dt>Min / Max</dt>
                      <dd>{r.minimum_value || "—"} ({r.minimum_period || "—"}) / {r.maximum_value || "—"} ({r.maximum_period || "—"})</dd>
                      <dt>Series count</dt>
                      <dd>{r.series_count}</dd>
                      {r.calculation_note && (<><dt>Calculation</dt><dd>{r.calculation_note}</dd></>)}
                      {r.caveat && (<><dt>Caveat</dt><dd>{r.caveat}</dd></>)}
                      {warnings.length > 0 && (
                        <>
                          <dt>Warnings</dt>
                          <dd><ul>{warnings.map((w) => <li key={w}>{w}</li>)}</ul></dd>
                        </>
                      )}
                      <dt>Raw source</dt>
                      <dd>{r.raw_source_files}</dd>
                      {r.review_comment && (<><dt>Review comment</dt><dd>{r.review_comment}</dd></>)}
                    </dl>
                  )}
                </td>
              </tr>
            );
          })}
        </tbody>
      </table>
    </div>
  );
}
