import { useEffect, useMemo, useState, type ComponentType } from "react";
import type { DataFile, Stage, StageNote, Exhibit } from "./lib/types.ts";
import { STAGES } from "./lib/types.ts";
import { readDashboard, writeDashboard, type Dashboard } from "./lib/urlState.ts";
import type { DashboardContext } from "./dashboards/types.ts";
import { Overview } from "./dashboards/Overview.tsx";
import { TrackFoundation } from "./dashboards/TrackFoundation.tsx";
import { TrackDegreeProduction } from "./dashboards/TrackDegreeProduction.tsx";
import { TrackGraduateTraining } from "./dashboards/TrackGraduateTraining.tsx";
import { TrackWorkforceEntry } from "./dashboards/TrackWorkforceEntry.tsx";
import { TrackRetentionImmigration } from "./dashboards/TrackRetentionImmigration.tsx";
import { TrackResearchOutput } from "./dashboards/TrackResearchOutput.tsx";
import { DashboardNavigation } from "./components/DashboardNavigation.tsx";
import { NewsTicker } from "./components/NewsTicker.tsx";
import { ExpandableMethods } from "./components/ChartFrame.tsx";
import { fetchNewsRss, type NewsItem } from "./lib/sources/rss.ts";
import { resolveNewsFeeds, NEWS_CLASSIFIER } from "./lib/newsFeeds.ts";

// Still deployed under evj@stanford.edu's Cloudflare account (see
// CLAUDE.md) — proxies the 4 news feeds that don't send their own
// Access-Control-Allow-Origin header. VITE_WORKER_URL overrides this for
// local Worker development (see worker/'s own README-equivalent notes).
const WORKER_URL = import.meta.env.VITE_WORKER_URL || "https://gtm-live-proxy.evjohnston.workers.dev";
// The "-alt" logo variants are the bare Tech Futures Lab wordmark, with no
// sub-brand text baked in — the old logo-light/dark-bg.png had "Global Tech
// Monitor" baked into the PNG itself, which no image edit here can retitle;
// "Global Talent Monitor" is instead the pagehead's own real <h1> text below.
import logoLightBg from "./assets/logos/logo-light-bg-alt.png";
import logoDarkBg from "./assets/logos/logo-dark-bg-alt.png";

const TRACK_BY_STAGE: Record<Stage, ComponentType<{ ctx: DashboardContext }>> = {
  foundation: TrackFoundation,
  "degree-production": TrackDegreeProduction,
  "graduate-training": TrackGraduateTraining,
  "workforce-entry": TrackWorkforceEntry,
  "retention-immigration": TrackRetentionImmigration,
  "research-output": TrackResearchOutput,
};

export default function App() {
  const [dashboard, setDashboard] = useState<Dashboard>(() => readDashboard());
  const [data, setData] = useState<DataFile | null>(null);
  const [dark, setDark] = useState<boolean>(() => {
    const saved = localStorage.getItem("gtm-theme");
    if (saved === "dark" || saved === "light") return saved === "dark";
    return window.matchMedia?.("(prefers-color-scheme: dark)").matches ?? false;
  });

  useEffect(() => {
    document.documentElement.dataset.theme = dark ? "dark" : "light";
    localStorage.setItem("gtm-theme", dark ? "dark" : "light");
  }, [dark]);

  useEffect(() => {
    writeDashboard(dashboard);
  }, [dashboard]);

  useEffect(() => {
    function onPopState() {
      setDashboard(readDashboard());
    }
    window.addEventListener("popstate", onPopState);
    return () => window.removeEventListener("popstate", onPopState);
  }, []);

  // One fetch, one static file — there's no live source behind this data
  // (see CLAUDE.md's "Ingestion" section). public/data/talent.json is
  // regenerated by `npm run import-talent-charts` whenever talent_charts/
  // gets a fresh export, and committed like any other file.
  useEffect(() => {
    fetch(`${import.meta.env.BASE_URL}data/talent.json`)
      .then((r) => r.json() as Promise<DataFile>)
      .then(setData)
      .catch(() => {});
  }, []);

  // The one thing in this app that IS live: real trade/policy press,
  // fetched once on page load (not on a timer — this isn't meant to read
  // as a streaming feed, same reasoning CLAUDE.md gives for why the old
  // quantum/AI app's 3-minute auto-refresh was removed). Never written to
  // a committed file, so it doesn't reopen the "data lives on its own
  // branch" problem the static-data architecture deliberately avoids.
  const [newsItems, setNewsItems] = useState<NewsItem[] | null>(null);
  useEffect(() => {
    fetchNewsRss(resolveNewsFeeds(WORKER_URL), NEWS_CLASSIFIER)
      .then(setNewsItems)
      .catch(() => setNewsItems([]));
  }, []);

  const exhibits = data?.exhibits ?? [];
  const exhibitsByStage = useMemo(() => {
    const by = Object.fromEntries(STAGES.map((s) => [s.id, [] as Exhibit[]])) as Record<Stage, Exhibit[]>;
    for (const e of exhibits) by[e.stage].push(e);
    for (const s of Object.keys(by) as Stage[]) by[s].sort((a, b) => a.order - b.order);
    return by;
  }, [exhibits]);
  const latestNote = useMemo(() => {
    const by: Partial<Record<Stage, StageNote>> = {};
    for (const n of data?.notes ?? []) { const c = by[n.stage]; if (!c || n.date > c.date) by[n.stage] = n; }
    return by;
  }, [data]);

  const generated = data?.generatedAt
    ? new Date(data.generatedAt).toLocaleString("en-US", { month: "short", day: "numeric", year: "numeric" })
    : "—";

  function navigate(next: Dashboard) {
    setDashboard(next);
    window.scrollTo({ top: 0, behavior: "smooth" });
  }

  const ctx: DashboardContext = { data, exhibits, exhibitsByStage, latestNote, dark, generated, dashboard, navigate };
  const Track = dashboard === "overview" ? null : TRACK_BY_STAGE[dashboard];

  return (
    <>
      <div className="topbar">
        <div className="topbar-inner">
          <img className="wordmark-logo" src={dark ? logoDarkBg : logoLightBg} alt="Tech Futures Lab" />
          <span className="topbar-meta">
            <span>● {data ? "static build" : "loading"}</span>
            <span title="Imported from talent_charts/ — see CLAUDE.md's Ingestion section">{generated}</span>
          </span>
          <button className="theme-toggle" onClick={() => setDark((d) => !d)} aria-label={dark ? "Switch to light mode" : "Switch to dark mode"} title={dark ? "Switch to light mode" : "Switch to dark mode"}>
            {dark ? "☀" : "☾"}
          </button>
        </div>
      </div>

      <NewsTicker items={newsItems ?? []} loading={newsItems === null} />

      <div className="wrap">
        <div className="pagehead">
          <div>
            <h1>Global Talent Monitor</h1>
            <div className="sub">STEM talent · foundation, degree production, graduate training, workforce entry, retention, research output</div>
          </div>
        </div>

        <DashboardNavigation active={dashboard} onNavigate={navigate} />

        {dashboard === "overview" && <Overview ctx={ctx} />}
        {Track && <Track ctx={ctx} />}

        <footer className="foot">
          <ExpandableMethods summary="Coverage and methods differ by stage.">
            Every number in this app traces to one exhibit in "The Great Talent Competition," a report built on
            primary data from NCES, NCSES/NSF, USCIS, DOL, the State Department, IIE, OECD, UNESCO, OpenAlex,
            Clarivate, the Nobel Foundation and ACM, Times Higher Education, WIPO, and USPTO PatentsView — see
            each panel's own "Open methodology" for that exhibit's specific source and URL. Data is imported from
            <code> talent_charts/</code> (that report's own R project) by <code>scripts/import-talent-charts.ts</code>,
            not fetched live — there is no faster-than-annual source behind any of these series, so re-run the
            import after a fresh export rather than expecting a nightly refresh. A handful of exhibits (marked in
            that script) are computed inline in the report's own R pipeline from other tables rather than a
            standalone CSV, and aren't yet ported.
          </ExpandableMethods>
          <div className="sig">Ideas Advancing Freedom</div>
        </footer>
      </div>
    </>
  );
}
